### PR TITLE
Testing with unsharded inputs

### PR DESCRIPTION
**Pull request by samnordmann**
Simplify the tests utility by testing locally at each rank. Slight speed-up of the tests.
The main but reasonable drawback is that each rank must have the full input available for testing.

### CODE REVIEW

**Comment by samnordmann** [comment]
check CI status here:
https://github.com/NVIDIA/Fuser/pull/1664

**Review by cowanmeg — APPROVED** [review]
Looks good! Thanks for refactoring this :D 
We should also move the megatron tests to use the new validate and execute method. I can do that later in a separate PR.

**Comment by samnordmann** [comment]
> Looks good! Thanks for refactoring this :D We should also move the megatron tests to use the new validate and execute method. I can do that later in a separate PR.

Sounds good !

**Comment by samnordmann** [comment]
Screenshot 2024-01-30 at 15 06 50

**Comment by samnordmann** [comment]
There is one failure here but seems unrelated:
https://github.com/NVIDIA/Fuser/pull/1664

**Pull request merged**
